Oas/Models/Subject/SubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Oas.Domain;

namespace Oas.Models.Subject
{
    public class SubjectViewModel
    {
        private Domain.Subject[] _subjects;

        public SubjectViewModel(IEnumerable<Domain.Subject> subjects) {
            this._subjects = subjects.ToArray();

            InitializeSubjectItems();
        }

        private void InitializeSubjectItems() {
            var subjects = new List<SubjectViewModelItem>();
            foreach (var subject in _subjects) {
                subjects.Add(new SubjectViewModelItem(subject.SubjectId, subject.Name, subject.SubjectType));
            }

            Subjects = subjects;
        }

        public IEnumerable<SubjectViewModelItem> Subjects { get; private set; }
    }

    public class SubjectViewModelItem
    {
        public SubjectViewModelItem(Guid subjectId, string subjectName, SubjectType subjectType) {
            SubjectId = subjectId;
            Name = subjectName;
            SubjectType = subjectType;
        }

        public Guid SubjectId { get; private set; }
        public string Name { get; private set; }
        public SubjectType SubjectType { get; private set; }
    }
}

Oas/Controllers/CourseController.cs
using System.Web.Mvc;
using Oas.Service.Interfaces;

namespace Oas.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private ICourseService _courseService;

        public CourseController(ICourseService courseService) {
            _courseService = courseService;
        }

        [Authorize(Roles = "Student, Teacher")]
        public ActionResult Index(string courseId) {
            var currentCourse = _courseService.GetCourse(courseId);
            return View(currentCourse);
        }

        [Authorize(Roles = "Student")]
        [ChildActionOnly]
        public ActionResult Subjects(string courseId) {
            var subjects = _courseService.GetCourseSubjects(courseId);
            return PartialView("_subjects", subjects);
        }
    }
}

Oas/Controllers/EvalController.cs
using System;
using System.Web.Mvc;
using Oas.Service.Interfaces;
using Oas.Service.Messages;

namespace Oas.Controllers
{
    public class EvalController : Controller
    {
        private IExamService _examService;

        public EvalController(IExamService examService)
        {
            _examService = examService;
        }
        [HttpGet]
        public ActionResult Index(string courseId)
        {
            var unevaluatedAnswerSheet = _examService.GetUnevaluatedAnswerSheets(courseId);
            return View(unevaluatedAnswerSheet);
        }
        [HttpGet]
        public ActionResult Perform(Guid answerSheetId)
        {
            var answerSheet = _examService.GetAnswerSheet(answerSheetId);
            return View(answerSheet);
        }
        [HttpPost]
        public ActionResult Perform(Guid answerSheetId, AnswerSheetEnvaluation evaluation)
        {
            _examService.EvaluateAnswerSheet(answerSheetId, evaluation);
            TempData["SlashMessage"] = "提交成功";
            return RedirectToAction("Index");
        }
    }
}

Oas/Controllers/ExamController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Oas.Domain;
using Oas.Domain.Service;
using Oas.Models.Exam;
using Oas.Service.Interfaces;

namespace Oas.Controllers
{
    public class ExamController : Controller
    {
        private IExamService _examService;
        private IQuestionService _questionService;

        public ExamController(IExamService examService, IQuestionService questionService) {
            _examService = examService;
            _questionService = questionService;
        }

        public ActionResult Index(string courseId) {
            return View();
        }

        public ActionResult StartNew(string courseId, string style) {
            var paper = _examService.GeneratePaper(courseId, style);
            return View(paper);
        }

        public ActionResult Submit(string courseId, ExamInputModel model) {
            var answerSheet = ConvertToAnswerSheet(model);

            var userId = User.Identity.GetUserId();
            var answerSheetId = _examService.UploadAnswerSheet(courseId, new Guid(userId), answerSheet);

            _examService.PreEvaluation(answerSheetId);
            TempData["SlashMessage"] = "提交成功，请等待老师为主观题打分";

            return RedirectToAction("Index", "Record");
        }

        public ActionResult DownloadAttachment(Guid questionId) {
            var question = _questionService.GetSubjectiveQuestion(questionId);
            return File(question.AttachmentPath, @"application/octet-stream", question.AttachmentName);
        }

        private AnswerSheet ConvertToAnswerSheet(ExamInputModel model)
        {
            var answerSheet = new AnswerSheet();

            foreach (var singleQuestion in model.SingleQuestions)
            {
                var item = new SelectableQuestionItem();
                item.QuestionId = singleQuestion.QuestionId;
                item.IsSingle = true;
                item.CheckedOptions.Add(new QuestionItemOption
                {
                    OptionId = singleQuestion.CheckedOption
                });
                answerSheet.SelectableQuestionAnswers.Add(item);
            }

            foreach (var multipleQuestion in model.MultipleQuestions)
            {
                var item = new SelectableQuestionItem();
                item.QuestionId = multipleQuestion.QuestionId;
                item.IsSingle = false;
                foreach (var option in multipleQuestion.CheckedOptions.Where(co => co.Checked))
                {
                    item.CheckedOptions.Add(new QuestionItemOption
                    {
                        OptionId = option.OptionId
                    });
                }
                answerSheet.SelectableQuestionAnswers.Add(item);
            }

            foreach (var subjectQuestion in model.SubjectiveQuestions)
            {
                var item = new SubjectiveQuestionItem();
                item.QuestionId = subjectQuestion.QuestionId;
                item.WriteDown = subjectQuestion.WriteDown;
                answerSheet.SubjectiveQuestionAnswers.Add(item);
            }

            return answerSheet;
        }
    }
}

Oas/Controllers/ExerciseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Oas.Models.Exercise;
using Oas.Service.Interfaces;

namespace Oas.Controllers
{
    public class ExerciseController : Controller
    {
        private IQuestionService _questionService;

        public ExerciseController(IQuestionService questionService) {
            _questionService = questionService;
        }

        public ActionResult Index(string courseId, Guid subjectId) {
            return View();
        }

        public ActionResult Perform(string courseId, Guid subjectId, QuestionType type) {
            if (type == QuestionType.Selectable) {
                return View("PerformSelectable");
            }

            if (type == QuestionType.Subjective) {
                return View("PerformSubjective");
            }

            throw new InvalidOperationException("wrong question type");
        }

        public ActionResult GetData(string courseId, Guid subjectId, QuestionType type) {
            if (type == QuestionType.Selectable) {
                var questions = _questionService.GetAllSelectableQuestion(courseId, subjectId)
                    .Select(q => new
                    {
                        questionId = q.QuestionId,
                        body = q.Body,
                        score = q.Score,
                        options = q.Options.Select(o => new
                        {
                            content = o.Content,
                            isRight = o.IsRight
                        }).ToArray()
                    });
                return Json(questions.ToArray(), JsonRequestBehavior.AllowGet);
            }

            if (type == QuestionType.Subjective) {
                var questions = _questionService.GetAllSubjectiveQuestion(courseId, subjectId)
                    .Select(q => new
                    {
                        questionId = q.QuestionId,
                        body = q.Body,
                        score = q.Score,
                        answer = q.Answer,
                        attachmentName = q.AttachmentName,
                        attachmentPath = Url.Action("DownloadAttachment", new { questionId = q.QuestionId})
                    });
                return Json(questions.ToArray(), JsonRequestBehavior.AllowGet);
            }

            throw new InvalidOperationException("wrong type.");
        }

        public ActionResult DownloadAttachment(Guid questionId) {
            var question = _questionService.GetSubjectiveQuestion(questionId);
            return File(question.AttachmentPath, @"application/octet-stream", question.AttachmentName);
        }
    }
}

Oas/Controllers/SubjectController.cs
using System;
using System.Web.Mvc;
using Oas.Domain;
using Oas.Models.Subject;
using Oas.Service.Interfaces;

namespace Oas.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class SubjectController : Controller
    {
        private ICourseService _courseService;

        public SubjectController(ICourseService courseService) {
            _courseService = courseService;
        }

        public ActionResult Index(string courseId) {
            var subjects = _courseService.GetCourseSubjects(courseId);
            var viewModel = new SubjectViewModel(subjects);

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create(string courseId) {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string courseId, Subject subject) {
            _courseService.CreateSubject(courseId, subject);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(Guid subjectId)
        {
            _courseService.DeleteSubject(subjectId);
            return RedirectToAction("Index");
        }
    }
}

Oas/Views/Shared/_course-layout.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="row">
    <div class="col-xs-6 col-sm-3" id="sidebar" role="navigation">
        @Html.Partial("_sidebar")
    </div>
    <div class="col-md-9" role="main">
        @RenderBody()
    </div>
</div>
@RenderSection("script", false)

Oas/Views/Shared/_courseLayout.cshtml
@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<div class="row">
    <div class="col-xs-6 col-sm-3" id="sidebar" role="navigation">
        @Html.Partial("_sidebar")
    </div>
    <div class="col-md-9" role="main">
        @RenderBody()
    </div>
</div>

Oas/Views/Shared/_footer.cshtml
<div class="container">
    <footer>
        <p class="pull-right"><a href="#">回到顶部</a></p>
        <p>© 2014 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
</div>

Oas/Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render(
        "~/bundles/jquery",
        "~/bundles/jquery-validation",
        "~/bundles/bootstrap")
</head>
<body>
@Html.Partial("_nav")
<div class="container" style="min-height: 700px;">
    @if (TempData.ContainsKey("FlashMessage"))
    {
        <div class="alert alert-info alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            @TempData["FlashMessage"]
        </div>
    }
    @RenderBody()
</div>

@Html.Partial("_footer")


<script type="text/javascript">
    $(document).ready(function() {
        $('.validation-summary-errors').addClass('alert alert-warning');
    });

    $(document).ready(function() {
        var root = $('#selectable-options');
        var formatTemplate = function(index) {
            var template =
                '<div class="input-group">' +
                    '<input type="hidden" name="Options.Index" value="' + index + '" />' +
                    '<span class="input-group-addon">' +
                    '<input type="checkbox" id="Options[' + index + '].IsRight" name="Options[' + index + '].IsRight" value="true">' +
                    '</span>' +
                    '<input type="text" class="form-control" id="Options[' + index + '].Content" name="Options[' + index + '].Content">' +
                    '<div class="input-group-btn">' +
                    '<button type="button" class="btn btn-default option-remove">移除</button>' +
                    '</div>' +
                    '</div>';
            return template;
        };
        $('#add-option').click(function() {
            var nextIndex = parseInt(root.attr('data-option-index'));
            var html = formatTemplate(nextIndex);
            root.append($(html));
            root.attr('data-option-index', nextIndex + 1);
        });
        $(document).on('click', '.option-remove', function() {
            var node = $(this).parent().parent();
            node.remove();
        });
    });
</script>
</body>
</html>

Oas/Views/Shared/_nav.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("职业技能培训系统模拟考核平台", "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("关于", "Index", "Home")</li>
                <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (Request.IsAuthenticated) {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">你好 @User.Identity.Name <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("修改信息", "Manage", "Account")</li>
                            <li class="active">@Html.ActionLink("注销", "LogOff", "Account")</li>
                        </ul>
                    </li>
                } else {
                    <li>@Html.ActionLink("登录", "Login", "Account")</li>
                    <li>@Html.ActionLink("注册", "Register", "Account")</li>
                }
            </ul>
        </div>
    </div>
</nav>

Oas/Views/Shared/_sidebar.cshtml
<div class="list-group">
    <h4 class="list-group-item active">学习管理</h4>
    @if (User.IsInRole("Teacher")) {
        <a href="@Url.Action("Index", "Subject")" class="list-group-item">科目管理</a>
        <a href="@Url.Action("Index", "Question")" class="list-group-item">题库管理</a>
        <a href="@Url.Action("Index", "Eval")" class="list-group-item">阅卷管理</a>
    }

    @if (User.IsInRole("Student")) {
        <a href="@Url.Action("Index", "Dashboard")" class="list-group-item">我的课程</a>
        <a href="@Url.Action("Index", "Record")" class="list-group-item">考试记录</a>
        Html.RenderAction("Subjects", "Course", new { courseId = ViewContext.RouteData.Values["courseId"] });
    }
</div>

Oas/Views/Shared/_subjects.cshtml
@model IEnumerable<Subject>

@foreach (var subject in Model) {
    if (subject.SubjectType == SubjectType.Normally)
    {
        <a href="@Url.Action("Index", "Exercise", new {subjectId = subject.SubjectId})" class="list-group-item">@subject.Name</a>
    }

    if (subject.SubjectType == SubjectType.Examination)
    {
        <a href="@Url.Action("Index", "Exam", new {subjectId = subject.SubjectId})" class="list-group-item">@subject.Name</a>
    }
}